language: node_js
node_js:
  - "stable"
install:
  - npm install -g mocha
  - npm install -g codecov
  - npm install -g nyc
  - npm install
after_success:
  npm run build:prod
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist/
  keep-history: true
  on:
    branch: master
notifications:
  email: false
