language: node_js
after_success:
  npm start
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist/
  keep-history: true
  on:
    branch: master
notifications:
  email: false
